[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "frame-src 'self' https://offerday.ai https://*.offerday.ai https://www.youtube.com https://www.youtube-nocookie.com;"
